on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:
    heroku_deploy_job:
        runs-on: ubuntu-latest
        name: A job to deploy django app to heroku container registry
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Deploy django to heroku
            uses: nyakaz73/heroku-django-deploy@v0.50 #Uses an action in the root directory
            id: deploy 
            with: 
              heroku_app_name : ${{ secrets.HEROKU_APP_NAME_MANIFEST }}
              heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
              heroku_email_address: 'tafadzwalnyamukapa@gmail.com'
              use_build_manifest: true
              
          #Use the output  from the hello step
          - name: Get the output status
            run: echo "${{ steps.deploy.outputs.status }}"